models:
  llm:
    provider: ollama
    model: llama3.2:1b
    host: http://localhost:11434
  vlm:
    provider: ollama
    model: moondream2
  stt:
    provider: whisper
    model: base
  tts:
    provider: piper
    model: "ai/tts/models/en_US-bmo_voice.onnx"
    speaker: null
    sample_rate: 22050
    executable: piper
    length_scale: 1
    noise_scale: 0.667
    noise_w_scale: 0.8
    volume: 1.0
    stream_wav_chunks: true

network:
  host: 0.0.0.0
  ws_port: 8001
  http_port: 8000

features:
  use_vad: false
  enable_memory: true
  enable_safety_filter: true
  allow_cloud_models: false
